on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via hetzner
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVERHOST }}
          username: ${{ secrets.SERVERUSER }}
          key: ${{ secrets.SERVERSSH }}
          script: |
            cd ~/CloudProject
            git pull
            docker compose down
            docker compose up -d --build
